# Generated by Django 3.2.18 on 2023-03-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('cityname',)},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('districtname',)},
        ),
        migrations.AlterModelTable(
            name='city',
            table='CITY',
        ),
        migrations.AlterModelTable(
            name='district',
            table='DISTRICT',
        ),
    ]
