# Generated by Django 3.2.18 on 2023-03-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20230302_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelTable(
            name='district',
            table='bankapp_district',
        ),
    ]
